### ISSUE TITLE
General To-Do List

### ISSUE THREAD

**Issue by streamyourcare** [streamyourcare/streamyourcare#1]
StreamYourCare's mission is to make care monitoring solutions that prevent loneliness, futility, negligence, and abuse at home and medical treatment facilities.

## **Short Term** (1-4 weeks)
- [ ] Add Voice Command setups
- [x] Fix chapter-fold plugin
- [x] Expand US & Global resource lists 
    - [x] Healthcare
    - [ ] Crisis prevention
    - [x] Mental health
    - [x] Digital literacy
- [ ] Optimize and include care stream guides for 
    - [x] Windows
    - [ ] Mac
    - [ ] iOS
    - [ ] Android.
- [x] Further introduce the care stream concept to social media through interviews, blogs, and videos.
- [ ] Release StreamYourCare 1.0: a free deployable system which lets you control when and how you livestream (**voice activated**: start, stop, privacy overlays, mute, send pre-made communications in chat with your voice while muted, and much more). 

## Medium Term (1-3 months)
- [ ] Provide several free alarm and alert configurations to use with affordable IoT sound/light devices. 
- [ ] Provide simple multi-lingual e-Books for seniors to print and take to care facilities.

## **Long Term** (3-5 months)
- [ ] Partner with organizations like PACE (Programs for All-Inclusive Care for the Elderly) to provide seniors with free monitoring/companionship capabilities.
-  [ ] Seek global care streaming opportunities for underrepresented individuals and groups around the world (501c3 partnership likely needed)
